In [8]:
# 1) Import pandas and read in the banklist.csv file into a dataframe called
# banks.
import pandas as pd
banks = pd.read_csv('banklist.csv')

In [7]:
# 2) Show the head of the dataframe
banks.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Fayette County Bank,Saint Elmo,IL,1802,"United Fidelity Bank, fsb",26-May-17,26-Jul-17
1,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,WI,30003,First-Citizens Bank & Trust Company,5-May-17,26-Jul-17
2,First NBC Bank,New Orleans,LA,58302,Whitney Bank,28-Apr-17,26-Jul-17
3,Proficio Bank,Cottonwood Heights,UT,35495,Cache Valley Bank,3-Mar-17,18-May-17
4,Seaway Bank and Trust Company,Chicago,IL,19328,State Bank of Texas,27-Jan-17,18-May-17

In [9]:
# 3) What are the column names?
banks.columns

Index(['Bank Name', 'City', 'ST', 'CERT', 'Acquiring Institution',
       'Closing Date', 'Updated Date'],
      dtype='object')

In [10]:
# 4. How many States (ST) are represented in this data set?
banks['ST'].nunique()

44

In [11]:
# 5. What are the top 5 states with the most failed banks?
banks['ST'].value_counts().head()

ST
GA    93
FL    75
IL    68
CA    41
MN    23
Name: count, dtype: int64

In [15]:
# 6) Get a list or array of all the states in the data set
banks['ST'].unique()

array(['IL', 'WI', 'LA', 'UT', 'NJ', 'AR', 'GA', 'PA', 'TN', 'WA', 'CO',
       'PR', 'FL', 'MN', 'CA', 'MD', 'OK', 'OH', 'SC', 'VA', 'ID', 'TX',
       'CT', 'AZ', 'NV', 'NC', 'KY', 'MO', 'KS', 'AL', 'MI', 'IN', 'IA',
       'NE', 'MS', 'NM', 'OR', 'NY', 'MA', 'SD', 'WY', 'WV', 'NH', 'HI'],
      dtype=object)

In [12]:
# 7) What are the top 5 acquiring institutions?
banks['Acquiring Institution'].value_counts().head()

Acquiring Institution
No Acquirer                            31
State Bank and Trust Company           12
First-Citizens Bank & Trust Company    11
Ameris Bank                            10
U.S. Bank N.A.                          9
Name: count, dtype: int64

In [13]:
#8) How many banks has the State Bank of Texas acquired? How many of
# them were actually in Texas?
banks[banks['Acquiring Institution'] == 'State Bank of Texas'].shape[0]

3

In [14]:
#9) What is the most common city in California for a bank to fail in?
banks[banks['ST'] == 'CA']['City'].value_counts().head(1)

City
Los Angeles    4
Name: count, dtype: int64